### ISSUE TITLE
Group issues by assembly / area / issue type / package

### ISSUE THREAD

**Issue by mtrive** [mtrive/ProjectAuditor#19]
Currently the only way to see the issues is in flat mode. It would be good to be able to group issues by assembly / area / issue type / package. I think some static analysis tool tend to group by issue type but I think we can experiment with different modes as well.

**Comment by mtrive** [comment]
Grouping by issue type is implemented and used by default when displaying script issues

**Comment by unitystevem** [comment]
I'm not sure that grouping by assembly/area/package are particularly relevant given the current state of the tool. You can filter/select by assembly/area which I think works better than grouping would, and since every package becomes an assembly, packages and assemblies are treated very similarly anyway.

**Comment by unitystevem** [comment]
I'm going to close this one just to clear the issue list up a bit. I think the filters we have make the need for the type of grouping described in this issue redundant.
