### ISSUE TITLE
Filter by currently selected platform

### ISSUE THREAD

**Issue by mtrive** [mtrive/ProjectAuditor#20]

**Comment by mtrive** [comment]
This might make sense for Project Settings only.

**Comment by unitystevem** [comment]
I think this does only make sense for project settings. And since there are very few platform-specific settings in the database right now, I'm not sure it makes sense to filter at all right now. I'll leave the issue open in case we one day add a bunch more platform specific checks, but for now I'm happy with it reporting the handful of iOS/Android issues regardless of the selected platform.

**Comment by unitystevem** [comment]
The more I think about this, the more I think we shouldn't filter, but just report on every platform which the install of Unity is capable of building (and for which we know of suitable platform-specific issues and recommendations). If my build settings are set to iOS but I also have Android build support installed, there's a very good chance I'm going to be targeting both platforms and want the tool to report issues for them both, without making me switch platforms and run it again.
