### ISSUE TITLE
Background/Lazy Assembly Analysis

### ISSUE THREAD

**Issue by mtrive** [mtrive/ProjectAuditor#83]
Analysis can take 30+ seconds depending on the project: we should only analyze Project Setting and Assembly-CSharp default assembly when Analyze button in pressed.
For the remaining assemblies, one of the following:
1. Analyze them in the background
2. Analyze a new assembly as soon as the user switches to a different one

**Comment by unitystevem** [comment]
I think this should be combined with putting in a new popup (like the thread selection one from Profile Analyzer) to select multiple combinations of assemblies. It should appear in the initial view of the window, and the Analyze button should only scan the selected assemblies.

**Comment by mtrive** [comment]
maybe, but I would not want to lose the one-button first-time user experience. Press Analyze and it just works.

**Comment by unitystevem** [comment]
If the selection box defaults to just the user assembly, then just opening the window and clicking Analyze will give the same user experience as it does now (except faster, because it will only look at the user assembly). Admittedly there'd be a drop down there as well, but still.

If you're REALLY against having a dropdown on the initial screen, perhaps the tool could still default to just the user assembly for that initial analysis, but hide the drop-down. Users who want to select some combination of packages would have to click Analyze once, and would then get selection options once that initial analysis is done. I'm not so much a fan of that option, because I'd like the user to have the (optional) power right from the start, but I don't feel particularly strongly about it.

**Comment by soraryu** [comment]
I would rather say: have it take 30s, but show a proper EditorUtility.DisplayProgressBar for it.

**Comment by mtrive** [comment]
I measured how long the scripts analysis take on 3 different projects. Here is the breakdown:

project            | compilation | assembly analysis | call tree construction |
-----------------------------------------------------------------------
kart-template |      5.9s        |             9s               |              1.6s                  |
boat attack     |      3.9s        |          22.9s             |              1.3s                  |
datas tale        |     12.2s       |          14.2s             |              1.7s                   |

so it looks like assembly analysis phase that would benefit the most from lazy/background processing.

As far as progress bar, I think the problem is that it's not yet visible during compilation. We should fix that.

**Comment by mtrive** [comment]
https://github.com/mtrive/ProjectAuditor/pull/113 fixed the progress bar

**Comment by mtrive** [comment]
background analysis implemented in https://github.com/mtrive/ProjectAuditor/pull/121.

There might be room for further improvements but I am closing this issue for the time being.
